import { StatusBar } from "expo-status-bar";
import * as NavigationBar from "expo-navigation-bar";
import React, { useEffect, useState } from "react";

// SAFE AREA PROVIDER (required!)
import { SafeAreaProvider } from "react-native-safe-area-context";
import OnEndReached from "./Core Components/FlatList/Phase 6/OnEndReached";
//import PullToRefreshBitch from "./Core Components/FlatList/Phase 6/PullToRefresh";
//import SearchFlatList from "./Core Components/FlatList/Lesson 4 - Search FlatList/SearchFlatList";
//import FinalFunctionButiNaman from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 6 - Final/Final";
//import MasMahirap from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 5/masmahirap";
//import SobrangDaliLang from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 4/anghirap";
//import AsyncWithPagination from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 3 - Async/withPagination";
//import AsyncRealApi from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 3 - Async/RealAPI";
//import AsyncWithApiFunctions from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 3 - Async/API";
//import FunctionTypesWithCrudDynamic from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 1/CrudDynamic";
//import FunctionTypeasContractsWithError from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Level 2/Basics";
//import FunctionTypesWithReducers from "./Core Components/FlatList/Phase 4/Function Types as Contracts/Reducers";
//import FunctionTypeContractsCheating from "./Core Components/FlatList/Phase 4/Function Types as Contracts/hard";
//import FunctionTypesWithAdding from "./Core Components/FlatList/Phase 4/Function Types as Contracts/adding";
//import TypedEventFunctions from "./Core Components/FlatList/Phase 4/Typed Event functions/Basics";
//import TypeFunctionMultiple from "./Core Components/FlatList/Phase 4/Typed Event functions/Multiple";
//import TypedEventFunctions from "./Core Components/FlatList/Phase 4/Typed Event functions/Basics";
//import HighlightingWithFlatListAkin from "./Core Components/FlatList/Phase 4/Highlight/Task1";
//import PressableRowsWithFlatList from "./Core Components/FlatList/Phase 4/Pressable Rows/basics";
//import FilteringAnotherLevelBasics from "./Core Components/FlatList/Lesson 5 - filtering/AnotherLevelBasics";
////import FlatListFilterCombined from "./Core Components/FlatList/Lesson 5 - filtering/anotherlevel";
//import FlatListFiltering from "./Core Components/FlatList/Lesson 5 - filtering/Filtering";
//import FlatListFilteringLastTry from "./Core Components/FlatList/Lesson 5 - filtering/Lasttry";
//import FlatListFiltering from "./Core Components/FlatList/Lesson 5 - filtering/Filtering";
//import SearchFlatList from "./Core Components/FlatList/Lesson 4 - Search FlatList/SearchFlatList";
//import FlatListHighlighting from "./Core Components/FlatList/Lesson 3 - Item Pressable/Highlighting";
//import ClickableFlatList from "./Core Components/FlatList/Lesson 3 - Item Pressable/Clickable";
//import FlatListWithLoadingTryKo from "./Core Components/FlatList/Lesson 2/TryKo";
//import FlatListWithLoading from "./Core Components/FlatList/Lesson 2/withLoading";
//import FlatListLesson1 from "./Core Components/FlatList/Level 1/Lesson 1";
//import DarkmodeandLightmodewithDropdown from "./Core Components/Dark mode and light mode/dropdown";
//import SortingComplete from "./Roadmap Before Flatlist/Sorting/Complete sort";
//import SortingBasics from "./Roadmap Before Flatlist/Sorting/sorting";
//import NullishCoalescingBasics from "./Roadmap Before Flatlist/Null Colishing/basics";
//import OptionalChainingBasics from "./Roadmap Before Flatlist/Optional Chaining/basics";
//import EveryBasics from "./Roadmap Before Flatlist/Every/Basics";
//import SomeBasics from "./Roadmap Before Flatlist/Some/basics";
//import StudentCRUD from "./Roadmap Before Flatlist/Destructuring/Lesson 3/flatlist.tsx/Quiz1";
//import DestructuringLesson3 from "./Roadmap Before Flatlist/Destructuring/Lesson 3/flatlist.tsx/flatlist";
//import DestructuringFinalLesson from "./Roadmap Before Flatlist/Destructuring/Lesson 2/Final";
//import DestructuringLesson1Basics from "./Roadmap Before Flatlist/Destructuring/Lesson 1/Basics";
//import FunctionLevel5Quiz2 from "./Roadmap Before Flatlist/Function/Level 5/Quiz2";
//import FunctionLevel5Quiz3 from "./Roadmap Before Flatlist/Function/Level 5/Quiz3";
//import FunctionLevel5Quiz1 from "./Roadmap Before Flatlist/Function/Level 5/Quiz1";
//import FunctionParentandChildren from "./Roadmap Before Flatlist/Function/Level 5/parent";
//import FunctionLevel4Task1 from "./Roadmap Before Flatlist/Function/Level 4/Task1";
//import FunctionLevel4Basics from "./Roadmap Before Flatlist/Function/Level 4/basic";
//import FunctionLevel3Task4 from "./Roadmap Before Flatlist/Function/Level 3/Task4";
//import FunctionLevel3Task3 from "./Roadmap Before Flatlist/Function/Level 3/Task3";
//import FunctionLevel3Task2 from "./Roadmap Before Flatlist/Function/Level 3/Task2";
//import FunctionLevel3Task1 from "./Roadmap Before Flatlist/Function/Level 3/task1";
//import FunctionLevel3WithButton from "./Roadmap Before Flatlist/Function/Level 3/withButton";
//import FunctionLevel3 from "./Roadmap Before Flatlist/Function/Level 3/basic";
//import FunctionsLevel2Task1 from "./Roadmap Before Flatlist/Function/Level 2/Task1";
//import FunctionLevel2 from "./Roadmap Before Flatlist/Function/Level 2/basic";
//import BasicFunctions from "./Roadmap Before Flatlist/Function/Level 1/BasicFunction";
//import FunctionLevel1Task1 from "./Roadmap Before Flatlist/Function/Level 1/Task1";
//import CrudGawaKo from "./Roadmap Before Flatlist/Find/Crud Another Level/CrudMyGawa";
//import RoadMapBeforeFlatlIstTask1 from "./Roadmap Before Flatlist/Tasks/Task1";
//import CrudOriginal from "./Roadmap Before Flatlist/Find/Crud Another Level/CrudOriginal";
//import CrudOriginalFake from "./Roadmap Before Flatlist/Find/Crud Another Level/crud";
//import CrudOriginal from "./Roadmap Before Flatlist/Find/Crud Another Level/crud";
//import CrudOriginal from "./Roadmap Before Flatlist/Find/Crud Another Level/CrudOriginal";
//import FindTask1 from "./Roadmap Before Flatlist/Find/Tasks/Task1";
//import StudentCRUD_NoFlatList from "./Roadmap Before Flatlist/Find/Crud Another Level/crud2";
//import CrudAnotherlevel from "./Roadmap Before Flatlist/Find/Crud Another Level/crud";
//import FindOpeningDetails from "./Roadmap Before Flatlist/Find/Lesson 3 - Opening Details/details";
//import FindOpeningTask1 from "./Roadmap Before Flatlist/Find/Lesson 3 - Opening Details/Tasks/Task1";
//import FindIndex from "./Roadmap Before Flatlist/Find/Lesson 4 - FindIndex/FindIndex";
//import FindLesson1 from "./Roadmap Before Flatlist/Find/Lesson 1 - Basics/basics";
//import Lesson2ProperDelete from "./Roadmap Before Flatlist/Find/Lesson 2 - Proper Deletion/ProperDelete";
//import FindQuiz1 from "./Roadmap Before Flatlist/Find/Lesson 2 - Proper Deletion/Tasks/quiz1";
//import SearchWithDebounceandRecent from "./Roadmap Before Flatlist/Filter/Lesson 4 - Search/withDebounce";
//import SafeRemoving from "./Roadmap Before Flatlist/Filter/Lesson 2 - Removing/SafeRemoving";
//import FilterUndo from "./Roadmap Before Flatlist/Filter/Lesson 3  - un/Undo";
//import FilterWithSearch from "./Roadmap Before Flatlist/Filter/Lesson 4 - Search/search";
//import FilterLesson2Removing from "./Roadmap Before Flatlist/Filter/Lesson 2 - Removing/Basic1";
//import DynamicRemoving from "./Roadmap Before Flatlist/Filter/Lesson 2 - Removing/RemovingDynamic";
//import FilterBasic2 from "./Roadmap Before Flatlist/Filter/Lesson1/Basic2";
//import FilterLesson1Basic3 from "./Roadmap Before Flatlist/Filter/Lesson1/Basic3";
//import FilterQuiz1 from "./Roadmap Before Flatlist/Filter/Lesson1/Quizzes/Quiz1";
//import FilterQuiz2 from "./Roadmap Before Flatlist/Filter/Lesson1/Quizzes/Quiz2";
//import FilterQuiz3 from "./Roadmap Before Flatlist/Filter/Lesson1/Quizzes/Quiz3";
//import FilterQuiz4 from "./Roadmap Before Flatlist/Filter/Lesson1/Quizzes/Quiz4";
//import AddingDynamic from "./Projects/Crud/Crud";
//import FilterLesson1 from "./Roadmap Before Flatlist/Filter/Lesson1/basics";
//import DynamicallyUpdating from "./Roadmap Before Flatlist/Spread/Updating Dynamically/dynamically update";
//import DynamicUpdating from "./Roadmap Before Flatlist/Spread/Updating Dynamically/UpdatingDynamic";
//import UpdatingField from "./Roadmap Before Flatlist/Spread/Lesson 4/UpdatingField";
//import SpreadDeepNested from "./Roadmap Before Flatlist/Spread/Lesson 5/DeepNested";
//import SpreadCopy from "./Roadmap Before Flatlist/Spread/Lesson1/copy";
//import SpreadBasicAdd from "./Roadmap Before Flatlist/Spread/Lesson 2/basicAdd";
//import SpreadCombiningArrays from "./Roadmap Before Flatlist/Spread/Lesson 3/CombiningArrays";
//import MapQuiz13 from "./Map/Lesson 5 - Basic trans/Quizzes/MiniShoppee";
//import MiniShoppee from "./Projects/MiniShoppee/MiniShoppee";
//import MapQuiz12 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz12";
//import CrudProject from "./Core Components/Projects/Crud/Crud";
//import MapQuiz12 from "./Core Components/Projects/Crud/Crud";
//import MapQuiz10 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz10";
//import AppWithEdit from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz11";
//import MapQuiz9 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz9";
//import MapQuiz8 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz8";
//import MapQuiz6 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz6";
//import MapQuiz7 from "./Map/Lesson 5 - Basic trans/Quizzes/Task7";
///mport MapInsideObjects from "./Map/Lesson 5 - Basic trans/MapInsideanotherObject";
//import MapQuiz4 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz4";
//import MapQuiz5 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz5";
// import MapQuiz1 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz1";
// import MapQuiz2 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz2";
//import MapQuiz3 from "./Map/Lesson 5 - Basic trans/Quizzes/Quiz3";
//import DestructuringinObjectsofArrays from "./Map/Lesson 5 - Basic trans/Destructuring";
//import PuttingLogicUsingMap from "./Map/Lesson 5 - Basic trans/PuttingLogic";
//import TransformingObject from "./Map/Lesson 5 - Basic trans/TransformObject";
//import AddingPropertyUsingMap from "./Map/Lesson 5 - Basic trans/AddProperty";
//import UpdatingValue from "./Map/Lesson 5 - Basic trans/UpdatingValue";
//import FindusingFilter from "./Find/Lesson 3 - Alerts/Delete";
//import FindConditionalUI from "./Find/Lesson 2/Highlighting";
//import FindAlerts from "./Find/Lesson 3 - Alerts/Alerts";
//import FindIntroduction from "./Find/Lesson 1 - Introdution/basics";
//import MappingArraysofObjects from "./Map/Level 4/Level4";
//import MappingQuiz2 from "./Map/Tasks/Task2";
//import MappingQuiz1 from "./Map/Tasks/Task1";
//import MapBasics from "./Map/Level 1/basic";
//import TransformationMap from "./Map/Level 2/transformingnumbers";
//import StringMapping from "./Map/Level 3/StringMapping";
//import NonMutatingArrays from "./Roadmap Before Flatlist/Arrays/Lesson 6 - Updating/NonMutating";
//import ArrayLength from "./Roadmap Before Flatlist/Arrays/Level 5 - Length/length";
//import ArraysObjects from "./Roadmap Before Flatlist/Arrays/Lesson 4 - Arrays of Objects/intro";
//import ArraysOfNumbers from "./Roadmap Before Flatlist/Arrays/Level 3 - Number/NumberArray";
//import ArraysTopic2 from "./Roadmap Before Flatlist/Arrays/Level 2 - String/CallingArray";
//import NestedObjectRemovingQuiz from "./Roadmap Before Flatlist/Objects/Lesson 5 -  Nested Object/Tasks/Task2";
//import RemovingNestedObject from "./Objects/Lesson 5 -  Nested Object/Removing/RemovingObject";
//import ObjectLesson4 from "./Core Components/Objects/Lesson 4/removingObjects";
//import NestedAddingObjectQuiz1 from "./Core Components/Objects/Lesson 5 -  Nested Object/Tasks/task1";
//import NestedObjectsUpdate from "./Core Components/Objects/Lesson 5 -  Nested Object/NestedUpdateBascics";
//import ObjectsNestedLesson5 from "./Core Components/Objects/Lesson 5 -  Nested Object/Intro";
//import ObjectsLesson4Quiz1 from "./Core Components/Objects/Lesson 4/Quizzes/Quiz1";
//import ObjectsAdding from "./Core Components/Objects/Lesson 4/AddingObjects";
//import ObjectsLesson3 from "./Core Components/Objects/Lesson 3/UpdatingObjectProperties";
//import ObjectsLesson2BracketNotation from "./Core Components/Objects/Lesson2/Bracket Notation";
//import ObjectsLevel1 from "./Core Components/Objects/Level 1/level1";
//import KurtLoginScreen from "./Core Components/Projects/Login/Login";
//import ActivityIndicatorTask12 from "./Core Components/ActivityIndicator/Task/Task12";
//import ActivityIndicatorTask6 from "./Core Components/ActivityIndicator/Task/Task6";
//import ActivityIndicatorTask5 from "./Core Components/ActivityIndicator/Task/Task5";
//import KurtLoginScreen from "./Core Components/ActivityIndicator/Task/Task10";
//import ArraysBasics from "./Core Components/Arrays/level1";
//import KeyboardAvoidingViewLesson3 from "./Core Components/KeyboardAvoidingView/withModal";
//import KeyboardAvoidingViewLesson2 from "./Core Components/KeyboardAvoidingView/Lesson2";
//import KeyboardAvoidingViewAndroid1 from "./Core Components/KeyboardAvoidingView/Lesson1";
//import StatusBarLesson2 from "./Core Components/StatusBar/lesson2";
//import StatusBarLesson1 from "./Core Components/StatusBar/Basics";
//import SafeAreaViewTask1 from "../Final/Core Components/SafeAreaView/Tasks/Task1";

// Your SafeAreaView practice screen
//import SafeAreaviewBasics from "./Core Components/SafeAreaView/Basics";

export default function App() {
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    NavigationBar.setBehaviorAsync("overlay-swipe");
    NavigationBar.setVisibilityAsync("hidden");

    // change background depending on theme
    NavigationBar.setBackgroundColorAsync(isDark ? "#000000" : "#FFFFFF");
  }, [isDark]);

  return (
    <SafeAreaProvider>
      <StatusBar hidden /> 
      <OnEndReached/>
    </SafeAreaProvider>
  );
}
